sequenceDiagram
firstMethod ->> secondMethod: call
secondMethod ->> testingService.callA: call
testingService.callA -->> secondMethod: return
secondMethod -->> firstMethod: return
firstMethod ->> fourthMethod: call
fourthMethod -->> firstMethod: return
